# SPDX-License-Identifier: Unlicense OR 0BSD
on: [push]

jobs:
  hxltm-testum:
    runs-on: ubuntu-latest
    name: hxltm-action ego testum
    steps:
      # @see https://github.com/actions/checkout
      - name: Checkout the git repository to the actions temporary host runner
        uses: actions/checkout@v2

      #### HXLTM export, multilingual formats __________________________________
      - name: "hxltmcli --help"
        uses: fititnt/hxltm-actionmain
        continue-on-error: true
        with:
          bin: "hxltmcli"
          args: "--help"

      - name: "hxltmdexml --help"
        uses: fititnt/hxltm-actionmain
        continue-on-error: true
        with:
          bin: "hxltmdexml"
          args: "--help"

      # Bonus: HXLStandard cli tools ___________________________________________
      # @see https://github.com/HXLStandard/libhxl-python/wiki/Command-line-tools
      - name: "hxlselect --help"
        uses: fititnt/hxltm-actionmain
        continue-on-error: true
        with:
          bin: "hxlselect"
          args: "--help"

      - name: "hxlspec --help"
        uses: fititnt/hxltm-actionmain
        continue-on-error: true
        with:
          bin: "hxlspec"
          args: "--help"

      #### HXLTM export, multilingual formats __________________________________
      - name: "hxltmcli --objectivum-TBX-Basim data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv data/exemplum/resultatum/de-hxltm/hxltm-exemplum-linguam.tbx"
        uses: fititnt/hxltm-action@main
        continue-on-error: true
        with:
          bin: "hxltmcli"
          args: "--objectivum-TBX-Basim"
          infile: data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv
          outfile: data/exemplum/resultatum/de-hxltm/hxltm-exemplum-linguam.tbx

      - name: "hxltmcli --objectivum-TMX data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv data/exemplum/resultatum/de-hxltm/hxltm-exemplum-linguam.tmx"
        uses: fititnt/hxltm-action@main
        continue-on-error: true
        with:
          bin: "hxltmcli"
          args: "--objectivum-TMX"
          infile: data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv
          outfile: data/exemplum/resultatum/de-hxltm/hxltm-exemplum-linguam.tmx

      - name: "hxltmcli --objectivum-UTX data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv data/exemplum/resultatum/de-hxltm/hxltm-exemplum-linguam.utx"
        uses: fititnt/hxltm-action@main
        continue-on-error: true
        with:
          bin: "hxltmcli"
          args: "--objectivum-UTX"
          infile: data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv
          outfile: data/exemplum/resultatum/de-hxltm/hxltm-exemplum-linguam.utx

      #### HXLTM import, multilingual formats __________________________________
      - name: 'hxltmdexml --agendum-linguam por-Latn@pt tests/hxltm-exemplum-linguam.tbx tests/result/objectivum-de-tbx.tm.hxl.csv'
        continue-on-error: true
        uses: fititnt/hxltm-action@main
        with:
          bin: "hxltmdexml"
          args: "--agendum-linguam por-Latn@pt"
          infile: data/exemplum/hxltm-exemplum-linguam.tbx
          outfile: data/exemplum/resultatum/de-tbx/hxltm-exemplum-linguam.tm.hxl.csv

      - name: 'hxltmdexml --agendum-linguam por-Latn@pt data/exemplum/hxltm-exemplum-linguam.tmx data/exemplum/resultatum/de-tmx/hxltm-exemplum-linguam.tm.hxl.csv'
        continue-on-error: true
        uses: fititnt/hxltm-action@main
        with:
          bin: "hxltmdexml"
          args: "--agendum-linguam por-Latn@pt"
          infile: data/exemplum/hxltm-exemplum-linguam.tmx
          outfile: data/exemplum/resultatum/de-tmx/hxltm-exemplum-linguam.tm.hxl.csv

      #### HXLTM ad hoc templated export _______________________________________
      # - name: "hxltmcli --objectivum-formulam data/README.🗣️.md --objectivum-linguam por-Latn@pt data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv data/README.por-Latn.md"
      - name: ".github/hxltm/hxltmcli.py --objectivum-formulam data/README.🗣️.md --objectivum-linguam por-Latn@pt data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv data/README.por-Latn.md"
        uses: fititnt/hxltm-action@main
        continue-on-error: true
        with:
          # bin: "hxltmcli"
          bin: ".github/hxltm/hxltmcli.py" # This is a local fork
          args: |
            --objectivum-formulam data/README.🗣️.md
            --objectivum-linguam por-Latn@pt
          infile: data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv
          outfile: data/README.por-Latn.md

      # .github/hxltm/hxltmcli.py --objectivum-formulam data/README.🗣️.md --objectivum-linguam por-Latn@pt data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv data/README.{[iso6393]}-{[iso115924]}.md

      - name: ".github/hxltm/hxltmcli.py --objectivum-formulam data/README.🗣️.md --objectivum-linguam eng-Latn@en data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv data/README.eng-Latn.md"
        uses: fititnt/hxltm-action@main
        continue-on-error: true
        with:
          bin: ".github/hxltm/hxltmcli.py"
          args: |
            --objectivum-formulam data/README.🗣️.md
            --objectivum-linguam eng-Latn@en
          infile: data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv
          outfile: data/README.eng-Latn.md

      - name: ".github/hxltm/hxltmcli.py --objectivum-formulam data/README.🗣️.md --objectivum-linguam lat-Latn@la data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv data/README.lat-Latn.md"
        uses: fititnt/hxltm-action@main
        continue-on-error: true
        with:
          bin: ".github/hxltm/hxltmcli.py"
          args: |
            --objectivum-formulam data/README.🗣️.md
            --objectivum-linguam lat-Latn@la
          infile: data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv
          outfile: data/README.lat-Latn.md

      - name: ".github/hxltm/hxltmcli.py --objectivum-formulam data/README.🗣️.md --objectivum-linguam spa-Latn@es data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv data/README.spa-Latn.md"
        uses: fititnt/hxltm-action@main
        continue-on-error: true
        with:
          bin: ".github/hxltm/hxltmcli.py"
          args: |
            --objectivum-formulam data/README.🗣️.md
            --objectivum-linguam spa-Latn@es
          infile: data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv
          outfile: data/README.spa-Latn.md

      - name: ".github/hxltm/hxltmcli.py --objectivum-formulam data/README.🗣️.md --objectivum-linguam arb-Arab@ar data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv data/README.arb-Arab.md"
        uses: fititnt/hxltm-action@main
        continue-on-error: true
        with:
          bin: ".github/hxltm/hxltmcli.py"
          args: |
            --objectivum-formulam data/README.🗣️.md
            --objectivum-linguam arb-Arab@ar
          infile: data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv
          outfile: data/README.arb-Arab.md

      - name: ".github/hxltm/hxltmcli.py --objectivum-formulam data/README.🗣️.md --objectivum-linguam hin-Deva@hi data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv data/README.hin-Deva.md"
        uses: fititnt/hxltm-action@main
        continue-on-error: true
        with:
          bin: ".github/hxltm/hxltmcli.py"
          args: |
            --objectivum-formulam data/README.🗣️.md
            --objectivum-linguam hin-Deva@hi
          infile: data/exemplum/hxltm-exemplum-linguam.tm.hxl.csv
          outfile: data/README.hin-Deva.md

      # TODO: test set is missing Russian language

      #### Upload results ______________________________________________________
      # @see https://github.com/actions/upload-artifact
      - uses: actions/upload-artifact@v2
        continue-on-error: true
        with:
          name: data
          path: data/
          retention-days: 5

      # TODO: https://github.com/actions/checkout#push-a-commit-using-the-built-in-token